// app/layout.js
import React from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from './Footer/page';
import { AuthProvider } from './AuthProvider';
import ServerNavbar from './Navbar/ServerNavbar';
import NavbarClient from '../Componets/NavbarClient';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-6`}
      >
        <AuthProvider>
        <NavbarClient />
          <div className="mt-8 min-h-screen">
          
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
